### ISSUE TITLE
What remains for methplotlib to be published?

### ISSUE THREAD

**Issue by endrebak** [wdecoster/methplotlib#8]
The TODO is not so extensive...

**Comment by wdecoster** [comment]
Actually, a preprint is already online since last week (https://www.biorxiv.org/content/10.1101/826107v1), and has been submitted for publication.

Further extensions would be digging into some statistics further, related to https://github.com/wdecoster/methplotlib/issues/7, but I don't really have some samples which would make that worthwhile. 
Also, other input formats (from other tools) would be relevant, but there is no community standard file format at the moment so I'm kinda waiting for that.

I hope to get back to that after finishing the grant I'm writing, but more likely would be January.

**Comment by endrebak** [comment]
Would you mind citing the bioinformatics application note and not the preprint? If you are asked to do any revisions.

Cool!

**Comment by wdecoster** [comment]
Oh, my bad, I'll have it corrected!

**Comment by endrebak** [comment]
Yeah, if you sent it in to Bioinformatics they would be happy to have one
more of their papers cited :)
